---
smtp:
  from: "maiafzal@gmail.com"
  username: ""
  password: ""
  smtp_server: "smtp.gmail.com"
  smtp_port: "465"

elasticsearch:
  username: "elastic"
  password: "elastic"
  host: "empms-es"
  port: 9200
